#!/bin/bash
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
charmm="charmm"
equi_prefix="step4_equilibration"
qmpr_prefix="step4.1_qmmmprep"
prod_prefix="step5_prod_umbrella"
prod_step="step5"
qmpackage="mndo97"

# Equilibration
$charmm < "${equi_prefix}.inp" > "${equi_prefix}.out"

# QM/MM input preparation
$charmm < "${qmpr_prefix}.inp" > "${qmpr_prefix}.out"

# Reaction Specs
rci=-2.0 #initial
rcf=2.0  #final
rcdel=0.1 #spacing
kmin=20
kmax=150

rc_mid=$(awk "BEGIN {print (${rci} + ${rcf})/2}")
winmax=$(awk "BEGIN {print int(((${rcf} - ${rci})/${rcdel}) + 1)}")

# Production Specs
cntmax=5 #MAXIMUM NUMBER OF CHUNKS PER WINDOW
win=1 #CHANGE HERE IF COUNTINUING STARTING WINDOW
cnt=1  #CHANGE HERE IF COUNTINUING A RUN AT SPECIFIC COUNTER IN ${win}


for ((i=$win;i<=$winmax;i++)); do
    while [ $cnt -le $cntmax ]; do
        pcnt=$(( cnt - 1 ))
        pwin=$(( i - 1 ))
        rc=$(awk "BEGIN {print ${rci} + ((${i} - 1) * ${rcdel})}")
        scale=$(awk "BEGIN {print 1 - ((2*($rc - $rc_mid)/($rcf - $rci))^2)}")
        kumb=$(awk "BEGIN {print $kmin + ($kmax - $kmin)*$scale}")
        istep=${prod_step}_window_${i}_${cnt}

        
        if   [[ ${cnt} -eq 1 && ${i} -eq 1 ]]; then
			pstep=${equi_prefix}
        elif [[ ${cnt} -eq 1 && ${i} -gt 1 ]]; then
            pstep=${prod_step}_window_${pwin}_${cntmax}
        elif [[ ${cnt} -gt 1  ]]; then
            pstep=${prod_step}_window_${i}_${pcnt}
        fi

        $charmm mdcnt=${cnt} mdqrst=${qrst} mdwin=${i} mdpcnt=${pcnt} mdpwin=${pwin} mdrc=${rc} mdkumb=${kumb} mdpstep=${pstep} mdistep=${istep}  ${qmpackage}=1 < "${prod_prefix}.inp" > "${istep}.out"
        cnt=$(( cnt + 1 ))
    done
done 

